language: elixir

cache:
  directories:
    - ~/.hex
    - ~/.mix
    - deps
    - _build/*/*.plt

elixir:
  - 1.4
  - 1.6

otp_release:
  - 19.3
  - 20.0

matrix:
  include:
    - otp_release: 20.0
      elixir: 1.5
    - otp_release: 18.3
      elixir: 1.4

install:
  - mix local.hex --force
  - mix deps.get

script:
  - mix test
  - MIX_ENV=test mix dialyzer --halt-exit-status
