language: elixir

cache:
  directories:
    - ~/.hex
    - ~/.mix
    - _build


matrix:
  include:
    - otp_release: 21.3
      elixir: 1.8
    - otp_release: 21.3
      elixir: 1.7
    - otp_release: 20.3
      elixir: 1.6
    - otp_release: 19.3
      elixir: 1.5
    - otp_release: 18.3
      elixir: 1.4

install:
  - mix local.hex --force
  - mix deps.get

script:
  - mix test
  - MIX_ENV=test mix dialyzer --halt-exit-status

# Leave only the .plt files in build
before_cache:
  - mix deps.clean --all --build
  - mix clean --build
